Website/FC15Website/urls.py
"""
Definition of urls for FC15Website.
"""
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles

from datetime import datetime
from django.conf.urls import url, handler404, handler500
import django.contrib.auth.views
from django.views.generic.base import RedirectView

from django.conf.urls import include
from django.contrib import admin
import FC15.views
admin.autodiscover()

handler404 = 'FC15.views.page_not_found'
handler500 = 'FC15.views.page_error'

# All urls available
urlpatterns = [
    # Basic pages
    url(r'^$', FC15.views.home, name = 'home'),
    url(r'^home/$', FC15.views.home, name = 'home'),
    url(r'^about_rule/$', FC15.views.about_rule, name = 'about_rule'),
    url(r'^about_story/$', FC15.views.about_story, name = 'about_story'),
    url(r'^about_sponsor/$', FC15.views.about_sponsor, name = 'about_sponsor'),
    url(r'^document/$', FC15.views.document, name = 'document'),
    url(r'^index/$', FC15.views.index, name = 'index'),
    url(r'^login/$', FC15.views.login, name = 'login'),
    url(r'^logout/$', FC15.views.logout, name = 'logout'),
    #url(r'^regist/$', FC15.views.regist, name = 'regist'),
    url(r'^upload/$', FC15.views.upload, name = 'upload'),
    url(r'^postblog/$', FC15.views.postblog, name = 'postblog'),
    url(r'^viewblogs/$', FC15.views.viewblogs, name = 'viewblogs'),
    url(r'^team/$', FC15.views.team, name = 'team'),
    url(r'^createteam/$', FC15.views.createteam, name = 'createteam'),
    url(r'^resetrequest/$', FC15.views.resetrequest, name = 'resetrequest'),
    url(r'^change/$', FC15.views.change, name = 'change'),
    url(r'^teamdetail/$', FC15.views.teamdetail, name = 'teamdetail'),
    url(r'^teamrequest/$', FC15.views.jointeamrequest, name = 'jointeamrequest'),
    url(r'^quitteam/$', FC15.views.quitteam, name = 'quitteam'),
    url(r'^dismissteam/$', FC15.views.dismissteam, name = 'dismissteam'),
    url(r'^playgame/$', FC15.views.playgame, name = 'playgame'),
    url(r'^unfinished/$', FC15.views.unfinished, name = 'unfinished'),
    url(r'^ui/$', FC15.views.ui, name = 'ui'),
    url(r'^ui_old/$', FC15.views.ui_old, name = 'ui_old'),
    url(r'^activateagain/$', FC15.views.activateagain, name = 'activateagain'),
    url(r'^rank/$', FC15.views.rank, name = 'rank'),

    # Register information from another website
    url(r'^postregist/$', FC15.views.postregist, name = 'postregist'),
 
    # Download file
    url(r'^sdkdownload/$', FC15.views.sdkdownload, name = 'sdkdownload'),
    url(r'^download_manual/$', FC15.views.download_manual, name = 'download_manual'),
    url(r'^download_0318ppt/$', FC15.views.download_0318ppt, name = 'download_0318ppt'),
    url(r'^download_dll/$', FC15.views.download_dll, name = 'download_dll'),

    # Error pages
    url(r'^404/$', FC15.views.page_not_found, name = 'pagenotfount'),
    url(r'^500/$', FC15.views.page_error, name = 'pageerror'),

    # Pages releated to pk(specific items in the database)
    url(r'^blogdetail/(?P<pk>[0-9]+)/$', FC15.views.blogdetail, name = 'blogdetail'),
    url(r'^blogedit/(?P<pk>[0-9]+)/$', FC15.views.blogedit, name = 'blogedit'),
    url(r'^blogdelete/(?P<pk>[0-9]+)/$', FC15.views.blogdelete, name = 'blogdelete'),
    url(r'^fileedit/(?P<pk>[0-9]+)/$', FC15.views.fileedit, name = 'fileedit'),
    url(r'^filedelete/(?P<pk>[0-9]+)/$', FC15.views.filedelete, name = 'filedelete'),
    url(r'^filedownload/(?P<pk>[0-9]+)/$', FC15.views.filedownload, name = 'filedownload'),
    url(r'^recorddownload/(?P<pk>[0-9]+)/$', FC15.views.recorddownload, name = 'recorddownload'),
    url(r'^recorddelete/(?P<pk>[0-9]+)/$', FC15.views.recorddelete, name = 'recorddelete'),
    url(r'^jointeam/(?P<pk>[0-9]+)/$', FC15.views.jointeam, name = 'jointeam'),
    url(r'^jointeamrequest/(?P<pk>[0-9]+)/$', FC15.views.jointeamrequest, name = 'jointeamrequest'),
    url(r'^mailactivate/(?P<activate_code>.*)/$', FC15.views.activate, name = 'activate'),
    url(r'^resetpassword/(?P<reset_code>.*)/$', FC15.views.resetpassword, name = 'resetpassword'),
    url(r'^acceptrequest/(?P<pk>[0-9]+)/$', FC15.views.acceptrequest, name = 'acceptrequest'),
    url(r'^rejectrequest/(?P<pk>[0-9]+)/$', FC15.views.rejectrequest, name = 'rejectrequest'),
    url(r'^replay/(?P<pk>[0-9]+)/$', FC15.views.replay, name = 'replay'),
    url(r'^selectai/(?P<pk>[0-9]+)/$', FC15.views.selectai, name = 'selectai'),
    url(r'^disselectai/(?P<pk>[0-9]+)/$', FC15.views.disselectai, name = 'disselectai'),

    # Admin page
	url(r'^admin/', admin.site.urls),

    # Favicon
    url(r'^favicon.ico$',RedirectView.as_view(url=r'static/favicon.ico')),
]

# Add static files
urlpatterns += staticfiles_urlpatterns()

Website/FC15/models.py
from django.db import models
from django.contrib import admin
import time, random, os


def user_dirpath():
    return ''


# Model which stores information of users
class UserInfo(models.Model):
    username = models.CharField(max_length = 100)
    realname = models.CharField(max_length = 100, default = '')
    password = models.CharField(max_length = 100)
    stu_number = models.CharField(max_length = 20)
    email = models.EmailField()
    team = models.CharField(max_length = 100, default = '', null = True, blank = True)
    activated = models.BooleanField(default = False)

    def __unicode__(self):
        return self.username


# Determines how to display class UserInfo in tables for admin
class UserInfoAdmin(admin.ModelAdmin):
    list_display = ('username', 'realname', 'stu_number', 'team', 'email')


# Model which stores information of teams
class TeamInfo(models.Model):
    teamname = models.CharField(max_length = 100)
    captain = models.CharField(max_length = 100)
    introduction = models.CharField(max_length = 500)
    members = models.IntegerField(default = 0)
    AI_selected = models.IntegerField(default = 0)


# Determines how to display class TeamInfo in tables for admin
class TeamInfoAdmin(admin.ModelAdmin):
    list_display = ('teamname', 'captain', 'members', 'introduction')


# Model for file uploaded
class FileInfo(models.Model):
    # Determines where the file will be saved
    def user_dirpath(instance, filename):
        now = time.strftime('%Y%m%d%H%M%S')
        exact_name = '{0}_{1}__{2}'.format(now, random.randint(0, 1000), filename)
        while os.path.exists('fileupload/{0}/{1}'.format(instance.username, exact_name)):
            exact_name = '{0}_{1}__{2}'.format(now, random.randint(0, 1000), filename)
        _path = 'fileupload/{0}/{1}'.format(instance.username, exact_name)
        instance.path = _path
        instance.origin_name = filename
        instance.exact_name = exact_name
        return './' + _path

    filename = models.CharField(max_length = 255)
    username = models.CharField(max_length = 100)
    teamname = models.CharField(max_length = 100, null = True, blank = True, default = '')
    description = models.CharField(max_length = 1000, null = True, blank = True, default = '')
    file = models.FileField(upload_to = user_dirpath)
    path = models.CharField(max_length = 500)
    origin_name = models.CharField(max_length = 255, default = filename)
    exact_name = models.CharField(max_length = 255, default = origin_name)
    timestamp = models.DateTimeField()
    selected = models.BooleanField(default = False)
    rank = models.IntegerField(default = 0)
    score = models.IntegerField(default = 0)

    is_compiled = models.CharField(max_length = 50, default = '', null = True, blank = True)
    is_compile_success = models.CharField(max_length = 50, default = '', null = True, blank = True)
    compile_result = models.CharField(max_length = 4096, default = '', null = True, blank = True)

    def __unicode__(self):
        return self.filename

    class Meta:
        verbose_name = 'FileInfo'
        ordering = ['-timestamp']


# Determines how to display class FileInfo in tables for admin
class FileInfoAdmin(admin.ModelAdmin):
    list_display = ('filename', 'username', 'is_compiled', 'is_compile_success', 'description')


# Model for AI (successfully compiled file)
class AIInfo(models.Model):
    name = models.CharField(max_length = 255) # filename
    author = models.CharField(max_length = 100) # username
    team = models.CharField(max_length = 100) # teamname
    description = models.CharField(max_length = 1000, null = True, blank = True)
    path = models.CharField(max_length = 500)
    enabled = models.BooleanField()


# Determines how to display class AIInfo in tables for admin
class AIInfoAdmin(admin.ModelAdmin):
    list_display = ('name', 'author', 'enabled')


# Model for record of game
class GameRecord(models.Model):
    username = models.CharField(max_length = 100) # the user who launched the game
    timestamp = models.DateTimeField()
    filename = models.CharField(max_length = 255) # name of the record file
    state = models.CharField(max_length = 50)
    AI1 = models.CharField(max_length = 20, blank = True, null = True, default = '')
    AI2 = models.CharField(max_length = 20, blank = True, null = True, default = '')
    AI3 = models.CharField(max_length = 20, blank = True, null = True, default = '')
    AI4 = models.CharField(max_length = 20, blank = True, null = True, default = '')
    AI1_name = models.CharField(max_length = 20, blank = True, null = True, default = '')
    AI2_name = models.CharField(max_length = 20, blank = True, null = True, default = '')
    AI3_name = models.CharField(max_length = 20, blank = True, null = True, default = '')
    AI4_name = models.CharField(max_length = 20, blank = True, null = True, default = '')

    class Meta:
        verbose_name = 'GameRecord'
        ordering = ['-timestamp']


# Determines how to display class AIInfo in tables for admin
class GameRecordAdmin(admin.ModelAdmin):
    list_display = ('username', 'timestamp', 'filename')


# Model for blogs
class BlogPost(models.Model):
    title = models.CharField(max_length = 150)
    username = models.CharField(max_length = 100)
    content = models.TextField()
    timestamp = models.DateTimeField()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = 'blogpost'
        ordering = ['-timestamp']


# Determines how to display class BlogPost in tables for admin
class BlogPostAdmin(admin.ModelAdmin):
    list_display = ('title', 'username', 'timestamp')


# Stores codes for activating with email
class EmailActivate(models.Model):
    username = models.CharField(max_length = 100)
    activate_string = models.CharField(max_length = 100)


# Determines how to display class EmailActivate in table for admin
class EmailActivateAdmin(admin.ModelAdmin):
    list_display = ('username', 'activate_string')


# Stores codes for reseting password with email
class PasswordReset(models.Model):
    username = models.CharField(max_length = 100)
    reset_string = models.CharField(max_length = 100)
    new_password = models.CharField(max_length = 10)


# Determines how to display class PasswordReset in table for admin
class PasswordResetAdmin(admin.ModelAdmin):
    list_display = ('username', 'reset_string')


# Requests to join or quit teams
class TeamRequest(models.Model):
    username = models.CharField(max_length = 100)
    destin_team = models.CharField(max_length = 100)
    message = models.CharField(max_length = 500)
    status = models.BooleanField(default = False) # False means the captain has not dealt with this request


# Determines how to display class TeamRequest in table for admin
class TeamRequestAdmin(admin.ModelAdmin):
    list_display = ('username', 'destin_team', 'status')


# Ranking list
class RankingList(models.Model):
    rank = models.IntegerField(default = 0)
    index = models.IntegerField(default = 0)
    name = models.CharField(max_length = 100, default = '')
    author = models.CharField(max_length = 100)
    teamname = models.CharField(max_length = 100, null = True, blank = True, default = '')
    description = models.CharField(max_length = 1000, null = True, blank = True, default = '')
    score = models.IntegerField(default = 0)


# Determines how to display class RankingList in table for admin
class RankingListAdmin(admin.ModelAdmin):
    list_display = ('rank', 'index', 'author', 'teamname', 'score')


# Register all the models to admin
admin.site.register(UserInfo, UserInfoAdmin)
admin.site.register(TeamInfo, TeamInfoAdmin)
admin.site.register(FileInfo, FileInfoAdmin)
admin.site.register(AIInfo, AIInfoAdmin)
admin.site.register(GameRecord, GameRecordAdmin)
admin.site.register(BlogPost, BlogPostAdmin)
admin.site.register(EmailActivate, EmailActivateAdmin)
admin.site.register(PasswordReset, PasswordResetAdmin)
admin.site.register(TeamRequest, TeamRequestAdmin)
admin.site.register(RankingList, RankingListAdmin)

Website/FC15/forms.py
#coding=utf-8
from django import forms
from django.contrib import messages
from FC15.models import UserInfo, FileInfo, BlogPost, TeamInfo

# All forms for this website

# For users to login
class UserLoginForm(forms.Form):
    username = forms.CharField(max_length = 100, widget = forms.TextInput(attrs = {'class': 'form_input'}))
    password = forms.CharField(max_length = 100, widget = forms.PasswordInput(attrs = {'class': 'form_input'}))


# For users to register
class UserRegistForm(forms.Form):
    username = forms.CharField(max_length = 100, widget = forms.TextInput)
    realname = forms.CharField(max_length = 100, widget = forms.TextInput)
    email = forms.CharField(widget = forms.EmailInput)
    stu_number = forms.CharField(max_length = 10, widget = forms.TextInput)
    password = forms.CharField(max_length = 100, widget = forms.PasswordInput)
    password_confirm = forms.CharField(max_length = 100, widget = forms.PasswordInput)


# For users to upload code
class FileUploadForm(forms.Form):
    filename = forms.CharField(max_length = 255)
    description = forms.CharField(max_length = 500, widget = forms.Textarea)
    file = forms.FileField()


class ResultUploadForm(forms.Form):
    file = forms.FileField()


# For users to post blogs
class BlogPostForm(forms.Form):
    title = forms.CharField(max_length = 100)
    content = forms.CharField(widget = forms.Textarea)


# For users to create teams
class CreateTeamForm(forms.Form):
    teamname = forms.CharField(max_length = 100)
    introduction = forms.CharField(max_length = 500, widget = forms.Textarea)


# For users to reset password
class ResetPasswordForm(forms.Form):
    username = forms.CharField(max_length = 100)
    email = forms.EmailField()


# For users to change password
class ChangeForm(forms.Form):
    email = forms.EmailField()
    old_password = forms.CharField(max_length = 100, widget = forms.PasswordInput)
    new_password = forms.CharField(max_length = 100, widget = forms.PasswordInput)
    confirm_password = forms.CharField(max_length = 100, widget = forms.PasswordInput)


# For users to send requests to join the team
class TeamRequestForm(forms.Form):
    destin_team = forms.CharField(max_length = 100)
    message = forms.CharField(max_length = 500, widget = forms.Textarea)


# Add a message and show it
# The function may be unable to use if the version of Django changes
def flash(request, title, text, level = 'info'):
    level_map = {
        'info': messages.INFO,
        'debug': messages.DEBUG,
        'success': messages.SUCCESS,
        'warning': messages.WARNING,
        'error': messages.ERROR
    }
    level = level_map[level]
    messages.add_message(request, level, text, extra_tags = title)
    return 'ok'

Website/FC15/templates/about_sponsor.html
{% extends "base.html" %}

{% block content %}

<!-- Here should be the introduction for the sponsor -->
<h1>Here should be the introduction for the sponsor</h1>

{% endblock %}

Website/FC15/templates/blogdetail.html
{% extends "base.html" %}

{% block content %}

<div class="banner" style="width: 100%; background: url('/static/images/{{ bgname }}') fixed center center no-repeat; background-size: cover; height: 1000px; margin: 0px 0px 0px 0px;">
    <div style="height: 1%; background-color: rgba(0, 0, 0, 0);"></div>
    <div class="fi" style="margin-left: 30%; width: 40%; margin-top: 20%; margin: auto; text-align: center;">
        <font size="150" color="white" face="微软雅黑">{{ post.title }}</font>
        <hr />
        <p style="font: bold 16px 微软雅黑">Posted by <el-tag type="warning">{{ post.username }}</el-tag> at <el-tag type="success">{{ post.timestamp }}</el-tag></p>
    </div>
    <div style="margin-top: 0px;">
    <textarea name="content" wrap="soft"  rows="20" disabled
        style="margin-top: 10px; font: 18px 微软雅黑; height: 60%; color: rgba(255, 255, 255, 1.0); margin-left: 20%; width: 60%; margin-bottom: 20px;  padding: 5px;  background: rgba(255, 255, 255, 0.3);  border-radius: 2px;  display: block;  padding: 0 9px;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);">{{ post.content }}</textarea>
    </div>
</div>

<!-- Banner 
<section id="banner">
	<div class="inner">
		<h2>Blog Detail</h2>
        <a href="/index/" class="button">Read more</a>
	</div>
</section>

<!-- Wrapper 
<section id="wrapper">
	<section id="one" class="wrapper spotlight style1">
		<div class="inner">
            <a href="" class="image"><img src="/static/images/pic02.jpg" alt="" /></a>
			<div class="content">
				<h2>{{ post.title }}</h2>
                <hr />
                <h5>Posted at {{ post.timestamp }}</h5>
                <p>Posted by {{ post.username }}</p>
			</div>
		</div>
	</section>

    <section id="two" class="wrapper alt spotlight style2">
		<div class="inner">
			<div class="content">
				<hr />
				<p>{{ post.content }}</p>
                <hr />
                <a href="/index/" class="button">Go back</a>
			</div>
		</div>
	</section>
</section>-->

{% endblock %}

Website/FC15/templates/change.html
{% extends "base.html" %}

{% block content %}

<div class="bg" style="width: 100%; background: url('/static/images/alter-bg.jpg') fixed center center no-repeat; background-size: cover; height: 950px; margin: 0px 0px 0px 0px;">
    <div style="height: 10%; background-color: rgba(0, 0, 0, 0);"></div>
    <div class="fi" style="margin-left: 30%; width: 40%; margin: auto; text-align: center;">
        <font size="100" color="white" face="微软雅黑">Welcome to FC15!</font>
        <p style="font: bold 18px 微软雅黑;">Please fill in the forms to alter you account.</p>
        <hr />
    </div>
    <div style="background-color: rgba(0, 0, 0, 0);">
        <div class="contact-input" style="margin-left: 30%; width: 40%; margin: auto; color: white; background-color: rgba(0, 0, 0, 0);">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form_input">
                    <label for="email" id="email" style="margin-left: 10%; font: 16px 微软雅黑;">Email</label>
                    <input type="email" name="email" class="contact-input"
                           style="color: rgba(255, 255, 255, 1.0); margin-left: 10%; width: 80%; overflow: hidden;margin-bottom: 20px;  padding: 5px;  background: rgba(255, 255, 255, 0.3);  border-radius: 2px;  display: block; height: 29px;  padding: 0 9px;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);"/>
                </div>
                <div class="form_input">
                    <label for="oldpw" id="oldpw" style="margin-left: 10%; font: 16px 微软雅黑;">Old password</label>
                    <input type="password" name="old_password" class="contact-input"
                           style="color: rgba(255, 255, 255, 1.0); margin-left: 10%; width: 80%; overflow: hidden;margin-bottom: 20px;  padding: 5px;  background: rgba(255, 255, 255, 0.3); border-radius: 2px;  display: block; height: 29px;  padding: 0 9px;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);"/>
                </div>
                <div class="form_input">
                    <label for="newpw" id="newpw" style="margin-left: 10%; font: 16px 微软雅黑;">New password</label>
                    <input type="password" name="new_password" class="contact-input"
                           style="color: rgba(255, 255, 255, 1.0); margin-left: 10%; width: 80%; overflow: hidden;margin-bottom: 20px;  padding: 5px;  background: rgba(255, 255, 255, 0.3); border-radius: 2px;  display: block; height: 29px;  padding: 0 9px;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);"/>
                </div>
                <div class="form_input">
                    <label for="confirm" id="confirm" style="margin-left: 10%; font: 16px 微软雅黑;">Confirm password</label>
                    <input type="password" name="confirm_password" class="contact-input"
                           style="color: rgba(255, 255, 255, 1.0); margin-left: 10%; width: 80%; overflow: hidden;margin-bottom: 20px;  padding: 5px;  background: rgba(255, 255, 255, 0.3); border-radius: 2px;  display: block; height: 29px;  padding: 0 9px;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);"/>
                </div>
                <input type="submit" value="Submit" class="el-button" style="width: 30%; margin-left: 35%;" onclick="return confirm('Are you sure to change you account information?')" />
            </form>
        </div>
    </div>
</div>

<!--
<el-container>
    <el-aside width="20%">

    </el-aside>
    <el-main>
        <div class="contact-input" style="margin-left: 0px;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form_input">
                    <label for="email" id="email">Email</label>
                    <input type="text" name="email" class="contact-input"
                           style="width: 80%; overflow: hidden;margin-bottom: 20px;  padding: 5px;  background: #eef7f9;  border-radius: 2px;  display: block; height: 29px;  padding: 0 9px;  color: #4d5a5e;  background: white;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);"/>
                </div>
                <div class="form_input">
                    <label for="oldpw" id="oldpw">Old password</label>
                    <input type="password" name="old_password" class="contact-input"
                           style="width: 80%; overflow: hidden;margin-bottom: 20px;  padding: 5px;  background: #eef7f9;  border-radius: 2px;  display: block; height: 29px;  padding: 0 9px;  color: #4d5a5e;  background: white;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);"/>
                </div>
                <div class="form_input">
                    <label for="newpw" id="newpw">New password</label>
                    <input type="password" name="new_password" class="contact-input"
                           style="width: 80%; overflow: hidden;margin-bottom: 20px;  padding: 5px;  background: #eef7f9;  border-radius: 2px;  display: block; height: 29px;  padding: 0 9px;  color: #4d5a5e;  background: white;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);"/>
                </div>
                <div class="form_input">
                    <label for="confirm" id="confirm">Confirm password</label>
                    <input type="password" name="confirm_password" class="contact-input"
                           style="width: 80%; overflow: hidden;margin-bottom: 20px;  padding: 5px;  background: #eef7f9;  border-radius: 2px;  display: block; height: 29px;  padding: 0 9px;  color: #4d5a5e;  background: white;  border: 1px solid #cfdfe3;  border-bottom-color: #d2e2e7;  border-radius: 2px;  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05), 0 1px rgba(255, 255, 255, 0.2);"/>
                </div>
                <input type="submit" value="Submit" class="el-button" onclick="return confirm('Are you sure to change you account information?')" />
            </form>
        </div>
    </el-main>
</el-container>
<!--
<section id="banner">
	<div class="inner">
	    <h2>Welcome {{ username }}!</h2>
	    <p>You can post your blog here</p>
	</div>
</section>
     
<section id="wrapper">
    <section id="one" class="wrapper spotlight style1">
		<div class="inner">
            <form method="post" enctype="multipart/form-data" style="left: 20px;">
            {% csrf_token %}
            <h1>Welcome {{ username }}! You can change your account information here.</h1>
            <br />
            <div class="form-group">
                <label for="id_email" class="col-md-2 control-label">Email</label>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label for="id_old_password" class="col-md-2 control-label">Old Password</label>
                {{ form.old_password }}
            </div>
            <div class="form-group">
                <label for="id_new_password" class="col-md-2 control-label">New password</label>
                {{ form.new_password }}
            </div>
           <div class="form-group">
                <label for="id_confirm_password" class="col-md-2 control-label">Confirm password</label>
                {{ form.confirm_password }}
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Submit" class="button" onclick="return confirm('Are you sure to change you account information?')" />
            </div>
            </form>
        </div>
    </section>
</section>
-->
{% endblock %}